import type { NextPage } from 'next'
import Head from 'next/head'
import Sidebar from "../components/Sidebar/Sidebar";
import Layout from "../components/Layout/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main></main>
    </div>
  )
}

export default Home
